In [1]:
import numpy as np
import pandas as pd
from sklearn import linear_model

In [3]:
df = pd.read_csv("homeprices.csv")
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [4]:
reg=linear_model.LinearRegression()
reg

LinearRegression()

In [5]:
reg.fit(df[['area']],df['price'])

LinearRegression()

In [8]:
reg.predict([[4500]])

array([791660.95890411])

In [9]:
#Save Model To a File Using Python Pickle
import pickle5 as pickle

In [10]:
with open('reg_pickle','wb') as file:
    pickle.dump(reg,file)

In [12]:
#Load Saved Model
with open('reg_pickle','rb') as file:
    mp = pickle.load(file)

In [13]:
mp.predict([[5000]])

array([859554.79452055])

In [21]:
#Save Trained Model Using joblib
import joblib as jb

In [22]:
jb.dump(reg, 'reg_joblib')

['reg_joblib']

In [23]:
#Load Saved Model
mj = jb.load('reg_joblib')

In [24]:
mj.predict([[5000]])

array([859554.79452055])